### ISSUE TITLE
Error during common_setup event phase

### ISSUE THREAD

**Issue by iceyninjapenguin** [dannydjdk/Ranged-Wireless-Redstone#4]
While plaing a modpack I made for 1.16.5 I was using the release of this but when loading it up it failed. Can anyone help me with this?\

Crash report:

---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 12/19/21 3:08 PM
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:85) [?:?] {re:classloading}
	at net.minecraftforge.fml.client.ClientModLoader.completeModLoading(ClientModLoader.java:188) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$null$1(Minecraft.java:508) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:securitycraft.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$16471/2071597451.run(Unknown Source) [?:?] {}
	at net.minecraft.util.Util.func_215077_a(Util.java:320) [?:?] {re:classloading,re:mixin}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:504) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:securitycraft.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$14940/401325603.accept(Unknown Source) [?:?] {}
	at net.minecraft.client.gui.ResourceLoadProgressGui.func_230430_a_(ResourceLoadProgressGui.java:113) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:481) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:977) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:securitycraft.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:securitycraft.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.2.20.jar:36.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$462/117248709.call(Unknown Source) [forge-1.16.5-36.2.20.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.lang.ClassLoader.findClass(ClassLoader.java:530) ~[?:1.8.0_51] {}
-- MOD rangedwirelessredstone --
Details:
	Caused by 0: java.lang.NoClassDefFoundError: com/dannyandson/tinyredstone/network/PanelCellSync
		at com.dannyandson.rangedwirelessredstone.network.ModNetworkHandler.registerMessages(ModNetworkHandler.java:48) ~[?:1.16.5-0.1.3] {re:classloading}
		at com.dannyandson.rangedwirelessredstone.setup.ModSetup.init(ModSetup.java:24) ~[?:1.16.5-0.1.3] {re:classloading}
		at com.dannyandson.rangedwirelessredstone.RangedWirelessRedstone$$Lambda$5299/632724332.accept(Unknown Source) ~[?:?] {}
		at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?] {}
		at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?] {}
		at net.minecraftforge.eventbus.EventBus$$Lambda$2925/233271622.invoke(Unknown Source) ~[?:?] {}
		at net.minecraftforge.eventbus.EventBus$$Lambda$3143/1496482328.invoke(Unknown Source) ~[?:?] {}
		at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
		at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[?:36.2] {re:classloading}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121) ~[?:?] {re:classloading}
		at net.minecraftforge.fml.ModContainer$$Lambda$3564/267375778.run(Unknown Source) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) ~[?:1.8.0_51] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) ~[?:1.8.0_51] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}

	Mod File: rangedwirelessredstone-1.16.5-0.1.3.jar
	Failure message: Ranged Wireless Redstone (rangedwirelessredstone) encountered an error during the common_setup event phase
		java.lang.NoClassDefFoundError: com/dannyandson/tinyredstone/network/PanelCellSync
	Mod Version: 1.16.5-0.1.3
	Mod Issue URL: NOT PROVIDED
	Exception message: java.lang.ClassNotFoundException: com.dannyandson.tinyredstone.network.PanelCellSync
Stacktrace:
	at java.lang.ClassLoader.findClass(ClassLoader.java:530) ~[?:1.8.0_51] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_51] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:106) ~[modlauncher-8.0.9.jar:?] {re:classloading}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51] {}
	at com.dannyandson.rangedwirelessredstone.network.ModNetworkHandler.registerMessages(ModNetworkHandler.java:48) ~[?:1.16.5-0.1.3] {re:classloading}
	at com.dannyandson.rangedwirelessredstone.setup.ModSetup.init(ModSetup.java:24) ~[?:1.16.5-0.1.3] {re:classloading}
	at com.dannyandson.rangedwirelessredstone.RangedWirelessRedstone$$Lambda$5299/632724332.accept(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2925/233271622.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$3143/1496482328.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[?:36.2] {re:classloading}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModContainer$$Lambda$3564/267375778.run(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1109165344 bytes (1057 MB) / 2267021312 bytes (2162 MB) up to 3817865216 bytes (3641 MB)
	CPUs: 8
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.4.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.20.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.20.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.20.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.20.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.20.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.20
	FML Language Providers: 
		javafml@36.2
		minecraft@1
	Mod List: 
		mowziesmobs-1.5.19.jar                            |Mowzie's Mobs                 |mowziesmobs                   |1.5.19              |SIDED_SETU|Manifest: NOSIGNATURE
		Wyrmroost-1.16.3-1.2.11.jar                       |Wyrmroost                     |wyrmroost                     |1.16.3-1.2.11       |SIDED_SETU|Manifest: NOSIGNATURE
		CC(FG1.16.5) v1.1.5.jar                           |Caves And Cliffs              |caves_and_cliffs              |1.1.5               |SIDED_SETU|Manifest: NOSIGNATURE
		AoA3-3.5.4-1.16.5.jar                             |Advent of Ascension           |aoa3                          |3.5.4               |SIDED_SETU|Manifest: NOSIGNATURE
		FunMod 5.3.jar                                    |Fun Mod                       |funmod                        |5.3                 |SIDED_SETU|Manifest: NOSIGNATURE
		Pehkui-3.0.1+1.16.5-forge.jar                     |Pehkui                        |pehkui                        |3.0.1+1.16.5-forge  |SIDED_SETU|Manifest: NOSIGNATURE
		callablehorses-1.16.3-1.2.1.4.jar                 |Callable Horses               |callablehorses                |1.2.1.4             |SIDED_SETU|Manifest: 8c:03:ac:7d:21:62:65:e2:83:91:f3:22:57:99:ed:75:78:1e:db:de:03:99:ef:53:3b:59:95:18:01:bc:84:a9
		ProjectE-1.16.5-PE1.0.1B.jar                      |ProjectE                      |projecte                      |PE1.0.1B            |SIDED_SETU|Manifest: NOSIGNATURE
		Mekanism-1.16.5-10.0.24.453.jar                   |Mekanism                      |mekanism                      |10.0.24             |SIDED_SETU|Manifest: NOSIGNATURE
		caelus-forge-1.16.5-2.1.3.2.jar                   |Caelus API                    |caelus                        |1.16.5-2.1.3.2      |SIDED_SETU|Manifest: NOSIGNATURE
		torohealth-1.16.4-forge-4.jar                     |ToroHealth                    |torohealth                    |NONE                |SIDED_SETU|Manifest: NOSIGNATURE
		lemonlib-1.3.6.jar                                |Lemon Lib                     |lemonlib                      |1.3.6               |SIDED_SETU|Manifest: NOSIGNATURE
		Waystones_1.16.5-7.6.4.jar                        |Waystones                     |waystones                     |7.6.4               |SIDED_SETU|Manifest: NOSIGNATURE
		Clumps-6.0.0.27.jar                               |Clumps                        |clumps                        |6.0.0.27            |SIDED_SETU|Manifest: NOSIGNATURE
		journeymap-1.16.5-5.7.3.jar                       |Journeymap                    |journeymap                    |5.7.3               |SIDED_SETU|Manifest: NOSIGNATURE
		Controlling-7.0.0.28.jar                          |Controlling                   |controlling                   |7.0.0.28            |SIDED_SETU|Manifest: NOSIGNATURE
		comforts-forge-1.16.5-4.0.1.3.jar                 |Comforts                      |comforts                      |1.16.5-4.0.1.3      |SIDED_SETU|Manifest: NOSIGNATURE
		citadel-1.8.1-1.16.5.jar                          |Citadel                       |citadel                       |1.8.1               |SIDED_SETU|Manifest: NOSIGNATURE
		alexsmobs-1.12.1.jar                              |Alex's Mobs                   |alexsmobs                     |1.12.1              |SIDED_SETU|Manifest: NOSIGNATURE
		NaturesCompass-1.16.5-1.9.1-forge.jar             |Nature's Compass              |naturescompass                |1.16.5-1.9.1-forge  |SIDED_SETU|Manifest: NOSIGNATURE
		YungsApi-1.16.4-Forge-13.jar                      |YUNG's API                    |yungsapi                      |1.16.4-Forge-13     |SIDED_SETU|Manifest: NOSIGNATURE
		potionsmaster-0.2.2-1.16.5-36.1.0.jar             |Potions Master                |potionsmaster                 |0.2.2-1.16.5-36.1.0 |SIDED_SETU|Manifest: NOSIGNATURE
		marvel_the_mod-1.5.jar                            |Marvel                        |marvel_themod                 |1.5                 |SIDED_SETU|Manifest: NOSIGNATURE
		DungeonCrawl-1.16.5-2.3.4.jar                     |Dungeon Crawl                 |dungeoncrawl                  |2.3.4               |SIDED_SETU|Manifest: NOSIGNATURE
		Bookshelf-Forge-1.16.5-10.3.29.jar                |Bookshelf                     |bookshelf                     |10.3.29             |SIDED_SETU|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		sophisticatedbackpacks-1.16.5-3.13.6.450.jar      |Sophisticated Backpacks       |sophisticatedbackpacks        |1.16.5-3.13.6.450   |SIDED_SETU|Manifest: NOSIGNATURE
		guardvillagers-1.16.5.1.2.6.jar                   |Guard Villagers               |guardvillagers                |1.2.6               |SIDED_SETU|Manifest: NOSIGNATURE
		secretrooms-1.16.5-1.1.3.jar                      |Secret Rooms 6                |secretroomsmod                |1.16.5-1.1.3        |SIDED_SETU|Manifest: NOSIGNATURE
		Morpheus-1.16.5-4.2.70.jar                        |Morpheus                      |morpheus                      |4.2.70              |SIDED_SETU|Manifest: NOSIGNATURE
		iceandfire-2.1.9-1.16.5.jar                       |Ice and Fire                  |iceandfire                    |2.1.9-1.16.5        |SIDED_SETU|Manifest: NOSIGNATURE
		rangedwirelessredstone-1.16.5-0.1.3.jar           |Ranged Wireless Redstone      |rangedwirelessredstone        |1.16.5-0.1.3        |ERROR     |Manifest: NOSIGNATURE
		MekanismGenerators-1.16.5-10.0.24.453.jar         |Mekanism: Generators          |mekanismgenerators            |10.0.24             |SIDED_SETU|Manifest: NOSIGNATURE
		StevesUniverse-MCv1.16.5-v1.3.7.jar               |StevesUniverse                |stevesuniverse                |1.3.7               |SIDED_SETU|Manifest: NOSIGNATURE
		inventorypets-1.16.5-2.0.15.jar                   |Inventory Pets                |inventorypets                 |2.0.15              |SIDED_SETU|Manifest: NOSIGNATURE
		carryon-1.16.5-1.15.5.15.jar                      |Carry On                      |carryon                       |1.15.5.15           |SIDED_SETU|Manifest: 8c:03:ac:7d:21:62:65:e2:83:91:f3:22:57:99:ed:75:78:1e:db:de:03:99:ef:53:3b:59:95:18:01:bc:84:a9
		forge-1.16.5-36.2.20-universal.jar                |Forge                         |forge                         |36.2.20             |SIDED_SETU|Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		Waddles-1.16.5-0.8.13.jar                         |Waddles                       |waddles                       |1.16.5-0.8.13       |SIDED_SETU|Manifest: NOSIGNATURE
		lavasponge-1.0.2-1.16.5.jar                       |LavaSponge                    |lavasponge                    |1.0.2-1.16.5        |SIDED_SETU|Manifest: NOSIGNATURE
		twilightforest-1.16.5-4.0.546-universal.jar       |The Twilight Forest           |twilightforest                |NONE                |SIDED_SETU|Manifest: NOSIGNATURE
		structure_gel-1.16.5-1.7.8.jar                    |Structure Gel API             |structure_gel                 |1.7.8               |SIDED_SETU|Manifest: NOSIGNATURE
		ironchest-1.16.5-11.2.21.jar                      |Iron Chests                   |ironchest                     |1.16.5-11.2.21      |SIDED_SETU|Manifest: NOSIGNATURE
		forge-1.16.5-36.2.20-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |SIDED_SETU|Manifest: NOSIGNATURE
		EnchantmentDescriptions-1.16.5-7.0.17.jar         |EnchantmentDescriptions       |enchdesc                      |7.0.17              |SIDED_SETU|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		Ping-1.16.4-1.6.9.jar                             |Ping                          |ping                          |1.16.4-1.6.9        |SIDED_SETU|Manifest: NOSIGNATURE
		BiomesOPlenty-1.16.5-13.1.0.477-universal.jar     |Biomes O' Plenty              |biomesoplenty                 |1.16.5-13.1.0.477   |SIDED_SETU|Manifest: NOSIGNATURE
		MekanismAdditions-1.16.5-10.0.24.453.jar          |Mekanism: Additions           |mekanismadditions             |10.0.24             |SIDED_SETU|Manifest: NOSIGNATURE
		inventorytotem_1.16.5-1.4.jar                     |Inventory Totem               |inventorytotem                |1.4                 |SIDED_SETU|Manifest: NOSIGNATURE
		baubles-1.8.7.1-1.16.5.jar                        |Baubles                       |baubles                       |1.8.7               |SIDED_SETU|Manifest: NOSIGNATURE
		dungeons_plus-1.16.5-1.1.5.jar                    |Dungeons Plus                 |dungeons_plus                 |1.1.5               |SIDED_SETU|Manifest: NOSIGNATURE
		majrusz-library-1.16.4-2.0.1.jar                  |Majrusz Library               |majrusz_library               |2.0.1               |SIDED_SETU|Manifest: NOSIGNATURE
		curios-forge-1.16.5-4.0.5.3.jar                   |Curios API                    |curios                        |1.16.5-4.0.5.3      |SIDED_SETU|Manifest: NOSIGNATURE
		rats-7.2.0-1.16.5.jar                             |Rats                          |rats                          |7.2.0               |SIDED_SETU|Manifest: NOSIGNATURE
		gravestone-1.16.5-1.0.6.jar                       |Gravestone Mod                |gravestone                    |1.16.5-1.0.6        |SIDED_SETU|Manifest: NOSIGNATURE
		collective-1.16.5-3.8.jar                         |Collective                    |collective                    |3.8                 |SIDED_SETU|Manifest: NOSIGNATURE
		Unique Enchantments-1.16.5-2.1.3.jar              |Unique Enchantments           |uniquee                       |2.1.3               |SIDED_SETU|Manifest: NOSIGNATURE
		[1.16.5] SecurityCraft v1.9.jar                   |SecurityCraft                 |securitycraft                 |v1.9                |SIDED_SETU|Manifest: NOSIGNATURE
		ToughAsNails-1.16.5-4.1.0.9-universal.jar         |Tough As Nails                |toughasnails                  |1.16.5-4.0.1.8      |SIDED_SETU|Manifest: NOSIGNATURE
		twoplayersonehorse-1.16.4-2.0.2.jar               |2 players 1 horse             |twoplayersonehorse            |1.16.4-2.0.2        |SIDED_SETU|Manifest: NOSIGNATURE
		Gobber2-Forge-1.16.5-2.3.52.jar                   |Gobber 2                      |gobber2                       |2.3.52              |SIDED_SETU|Manifest: NOSIGNATURE
		obfuscate-0.6.2-1.16.3.jar                        |Obfuscate                     |obfuscate                     |0.6.2               |SIDED_SETU|Manifest: e1:59:1a:56:ec:97:b3:d0:b3:4b:25:06:1f:83:b0:f4:fd:0c:24:e3:6d:ea:94:b1:9f:22:b0:38:13:60:88:ea
		vehicle-mod-0.45.2-1.16.3.jar                     |MrCrayfish's Vehicle Mod      |vehicle                       |0.45.2              |SIDED_SETU|Manifest: NOSIGNATURE
		BetterStrongholds-1.16.4-1.2.1.jar                |YUNG's Better Strongholds     |betterstrongholds             |1.16.4-1.2.1        |SIDED_SETU|Manifest: NOSIGNATURE
		MekanismTools-1.16.5-10.0.24.453.jar              |Mekanism: Tools               |mekanismtools                 |10.0.24             |SIDED_SETU|Manifest: NOSIGNATURE
		majruszs-difficulty-1.16.4-1.1.0.jar              |Majrusz's Progressive Difficul|majruszs_difficulty           |1.1.0               |SIDED_SETU|Manifest: NOSIGNATURE
		curiouselytra-forge-1.16.5-4.0.2.4.jar            |Curious Elytra                |curiouselytra                 |1.16.5-4.0.2.4      |SIDED_SETU|Manifest: NOSIGNATURE
		mountedpearl-1.16.3-1.0.0.jar                     |Mounted Pearl                 |mountedpearl                  |1.16.3-1.0.0        |SIDED_SETU|Manifest: 1f:47:ac:b1:61:82:96:b8:47:19:16:d2:61:81:11:60:3a:06:4b:61:31:56:7d:44:31:1e:0c:6f:22:5b:4c:ed
		moredragoneggs-2.3.jar                            |More Dragon Eggs              |moredragoneggs                |2.3                 |SIDED_SETU|Manifest: NOSIGNATURE
		Craftable-Golden-Apples-1.16.jar                  |Craftable Enchanted Golden App|muzuly_craftableenchantedgolde|1.0                 |SIDED_SETU|Manifest: NOSIGNATURE
		byg-1.3.5.jar                                     |Oh The Biomes You'll Go       |byg                           |1.3.4               |SIDED_SETU|Manifest: NOSIGNATURE
		xlfoodmod-1.16.4-1.2.0.jar                        |XL Food Mod                   |xlfoodmod                     |1.16.4-1.2.0        |SIDED_SETU|Manifest: NOSIGNATURE
		Marvel-a1.4.jar                                   |Marvel Mod                    |marvel                        |a1.4                |SIDED_SETU|Manifest: NOSIGNATURE
		Craftable Horse Armour  Saddle-1.16.5-1.7--Forge.j|CHA&S - Craftable Horse Armour|craftablehorsearmour          |1.7                 |SIDED_SETU|Manifest: NOSIGNATURE
		CraftableTotemOfUndying-1.16.5-1.2.2.jar          |Craftable Totem Of Undying    |craftabletotemofundying       |1.2.2               |SIDED_SETU|Manifest: NOSIGNATURE
		switchbow-1.7.jar                                 |Switch-Bow                    |switchbow                     |1.7                 |SIDED_SETU|Manifest: NOSIGNATURE
		BetterMineshafts-Forge-1.16.4-2.0.4.jar           |YUNG's Better Mineshafts      |bettermineshafts              |1.16.4-2.0.4        |SIDED_SETU|Manifest: NOSIGNATURE
		Unique Enchantments Base-1.16.5-1.1.1.jar         |Unique Enchantments Base      |uniquebase                    |1.1.1               |SIDED_SETU|Manifest: NOSIGNATURE
	Crash Report UUID: c8ec0eae-e07b-4074-9a61-7b9ca2eeb59d

**Comment by dannydjdk** [comment]
Thanks for the report! It looks like I may have introduced a hard dependency to Tiny Redstone in the last update. I should have a fix for this soon.

**Comment by dannydjdk** [comment]
Fixed in latest version in each of the 3 Minecraft versions supported.
